### ISSUE TITLE
(update_posts.sh) Server change not pushed yet

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/latex.gs.hs.kr#1]
서버에서 update_posts.sh 를 chmod 775 하고 commit 했는데, 이건 아직 push 하지 못했습니다.

Debian 에서는 git push origin master 하면 username 하고 password 치면 잘 commit 됐는데, 여기 서버는 CentOS라서 뭔가 다른가 봅니다. git push origin master 하면 403 forbidden 이 뜹니다. 그래서 이걸 해결하려고 `.git/config` 에서 `url`을 좀 바꾼 적이 있었는데, 그렇게 하면 **매번 git pull 할 때마다 passphrase를 요구**해서 crontab을 못 돌렸습니다.

으 어떻게 해야 잘 git push origin master 할 수 있을까요...

**Comment by seungwonpark** [comment]
으아 이것때문에 글 작성 기능도 안된다

**Comment by seungwonpark** [comment]
헐 git 버전이 낮아서 그런가
현재 2.10.0 이고, 전에 말했던 Debian 에서는 2.1.4 인데 지금 이 서버에서는 1.7.1이다
업데이트를 해봐야겠다

**Comment by seungwonpark** [comment]
일단 2.10.0 버전의 git 설치하는 데에는 성공했습니다.

**Comment by seungwonpark** [comment]
그런데 crontab에서는 git 과 jekyll 에 대해 command not found 가 나온다. 뭐지

**Comment by seungwonpark** [comment]
`update_posts.sh`에서 PATH를 설정했다.
`PATH=/bin/date:/usr/local/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/bin`
 그 결과 git 은 잘 되는데, jekyll 은 여전히 오류...
로그는 다음과 같다.

```
Started updating posts...
Tue Sep 20 17:45:01 KST 2016
Updating posts and website...
Already up-to-date.
/usr/local/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'jekyll' (>= 0.a) among 11 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0', execute `gem env` for more information
    from /usr/local/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/jekyll:22:in `<main>'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by seungwonpark** [comment]
`GEM_PATH`를 고치면 될 것 같다

**Comment by seungwonpark** [comment]
jekyll requirements 중 하나인 node를 안 깔아서 그런가

**Comment by seungwonpark** [comment]
**해결완료**

@CSNE 님이 제안하신 대로

> crontab으로는 path를 못 찾고 있으니 아예 crontab이 사용자처럼(?) 동작하게 하자

를 하기 위해, [여기](http://unix.stackexchange.com/a/89596)에 나온대로

`SHELL=/bin/bash` 를 crontab에 추가하니 드디어 제대로 된다!!!

**Comment by seungwonpark** [comment]
아 정확히는 `source $HOME/.bash_profile;` 도 추가했었음. 이거 잠깐 없애보니까 다시 안됨.

```
SHELL=/bin/bash

0 * * * * source $HOME/.bash_profile;  /var/www/source/update_files.sh
* * * * * source $HOME/.bash_profile;  /var/www/source/update_posts.sh
```
